services:
  - type: web
    name: smartclass-backend
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGIN
        value: http://localhost:3000
      - key: DB_URL
        value: jdbc:h2:mem:smartclassdb
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        value: ""
